// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pool.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListPoolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoolsRequest) Reset() {
	*x = ListPoolsRequest{}
	mi := &file_pool_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoolsRequest) ProtoMessage() {}

func (x *ListPoolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pool_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoolsRequest.ProtoReflect.Descriptor instead.
func (*ListPoolsRequest) Descriptor() ([]byte, []int) {
	return file_pool_proto_rawDescGZIP(), []int{0}
}

func (x *ListPoolsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreatePoolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PoolMode      string                 `protobuf:"bytes,3,opt,name=pool_mode,json=poolMode,proto3" json:"pool_mode,omitempty"`
	TotalLimit    int64                  `protobuf:"varint,4,opt,name=total_limit,json=totalLimit,proto3" json:"total_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePoolRequest) Reset() {
	*x = CreatePoolRequest{}
	mi := &file_pool_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePoolRequest) ProtoMessage() {}

func (x *CreatePoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pool_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePoolRequest.ProtoReflect.Descriptor instead.
func (*CreatePoolRequest) Descriptor() ([]byte, []int) {
	return file_pool_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePoolRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreatePoolRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePoolRequest) GetPoolMode() string {
	if x != nil {
		return x.PoolMode
	}
	return ""
}

func (x *CreatePoolRequest) GetTotalLimit() int64 {
	if x != nil {
		return x.TotalLimit
	}
	return 0
}

type GetPoolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolId        string                 `protobuf:"bytes,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPoolRequest) Reset() {
	*x = GetPoolRequest{}
	mi := &file_pool_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPoolRequest) ProtoMessage() {}

func (x *GetPoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pool_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPoolRequest.ProtoReflect.Descriptor instead.
func (*GetPoolRequest) Descriptor() ([]byte, []int) {
	return file_pool_proto_rawDescGZIP(), []int{2}
}

func (x *GetPoolRequest) GetPoolId() string {
	if x != nil {
		return x.PoolId
	}
	return ""
}

type DeletePoolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolId        string                 `protobuf:"bytes,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePoolRequest) Reset() {
	*x = DeletePoolRequest{}
	mi := &file_pool_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePoolRequest) ProtoMessage() {}

func (x *DeletePoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pool_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePoolRequest.ProtoReflect.Descriptor instead.
func (*DeletePoolRequest) Descriptor() ([]byte, []int) {
	return file_pool_proto_rawDescGZIP(), []int{3}
}

func (x *DeletePoolRequest) GetPoolId() string {
	if x != nil {
		return x.PoolId
	}
	return ""
}

func (x *DeletePoolRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type JoinPoolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolId        string                 `protobuf:"bytes,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	ProfileId     string                 `protobuf:"bytes,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinPoolRequest) Reset() {
	*x = JoinPoolRequest{}
	mi := &file_pool_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinPoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinPoolRequest) ProtoMessage() {}

func (x *JoinPoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pool_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinPoolRequest.ProtoReflect.Descriptor instead.
func (*JoinPoolRequest) Descriptor() ([]byte, []int) {
	return file_pool_proto_rawDescGZIP(), []int{4}
}

func (x *JoinPoolRequest) GetPoolId() string {
	if x != nil {
		return x.PoolId
	}
	return ""
}

func (x *JoinPoolRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

type LeavePoolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolId        string                 `protobuf:"bytes,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	ProfileId     string                 `protobuf:"bytes,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeavePoolRequest) Reset() {
	*x = LeavePoolRequest{}
	mi := &file_pool_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeavePoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeavePoolRequest) ProtoMessage() {}

func (x *LeavePoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pool_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeavePoolRequest.ProtoReflect.Descriptor instead.
func (*LeavePoolRequest) Descriptor() ([]byte, []int) {
	return file_pool_proto_rawDescGZIP(), []int{5}
}

func (x *LeavePoolRequest) GetPoolId() string {
	if x != nil {
		return x.PoolId
	}
	return ""
}

func (x *LeavePoolRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

type ListMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolId        string                 `protobuf:"bytes,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersRequest) Reset() {
	*x = ListMembersRequest{}
	mi := &file_pool_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersRequest) ProtoMessage() {}

func (x *ListMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pool_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersRequest.ProtoReflect.Descriptor instead.
func (*ListMembersRequest) Descriptor() ([]byte, []int) {
	return file_pool_proto_rawDescGZIP(), []int{6}
}

func (x *ListMembersRequest) GetPoolId() string {
	if x != nil {
		return x.PoolId
	}
	return ""
}

type ListPoolBlocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolId        string                 `protobuf:"bytes,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoolBlocksRequest) Reset() {
	*x = ListPoolBlocksRequest{}
	mi := &file_pool_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoolBlocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoolBlocksRequest) ProtoMessage() {}

func (x *ListPoolBlocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pool_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoolBlocksRequest.ProtoReflect.Descriptor instead.
func (*ListPoolBlocksRequest) Descriptor() ([]byte, []int) {
	return file_pool_proto_rawDescGZIP(), []int{7}
}

func (x *ListPoolBlocksRequest) GetPoolId() string {
	if x != nil {
		return x.PoolId
	}
	return ""
}

type BlockPoolCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolId        string                 `protobuf:"bytes,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockPoolCategoryRequest) Reset() {
	*x = BlockPoolCategoryRequest{}
	mi := &file_pool_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockPoolCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockPoolCategoryRequest) ProtoMessage() {}

func (x *BlockPoolCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pool_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockPoolCategoryRequest.ProtoReflect.Descriptor instead.
func (*BlockPoolCategoryRequest) Descriptor() ([]byte, []int) {
	return file_pool_proto_rawDescGZIP(), []int{8}
}

func (x *BlockPoolCategoryRequest) GetPoolId() string {
	if x != nil {
		return x.PoolId
	}
	return ""
}

func (x *BlockPoolCategoryRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type UnblockPoolCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolId        string                 `protobuf:"bytes,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockPoolCategoryRequest) Reset() {
	*x = UnblockPoolCategoryRequest{}
	mi := &file_pool_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockPoolCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockPoolCategoryRequest) ProtoMessage() {}

func (x *UnblockPoolCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pool_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockPoolCategoryRequest.ProtoReflect.Descriptor instead.
func (*UnblockPoolCategoryRequest) Descriptor() ([]byte, []int) {
	return file_pool_proto_rawDescGZIP(), []int{9}
}

func (x *UnblockPoolCategoryRequest) GetPoolId() string {
	if x != nil {
		return x.PoolId
	}
	return ""
}

func (x *UnblockPoolCategoryRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type GetCreditsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolId        string                 `protobuf:"bytes,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	ProfileId     string                 `protobuf:"bytes,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCreditsRequest) Reset() {
	*x = GetCreditsRequest{}
	mi := &file_pool_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCreditsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCreditsRequest) ProtoMessage() {}

func (x *GetCreditsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pool_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCreditsRequest.ProtoReflect.Descriptor instead.
func (*GetCreditsRequest) Descriptor() ([]byte, []int) {
	return file_pool_proto_rawDescGZIP(), []int{10}
}

func (x *GetCreditsRequest) GetPoolId() string {
	if x != nil {
		return x.PoolId
	}
	return ""
}

func (x *GetCreditsRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

type FriendPool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,2,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	PoolMode      string                 `protobuf:"bytes,4,opt,name=pool_mode,json=poolMode,proto3" json:"pool_mode,omitempty"`
	TotalLimit    int64                  `protobuf:"varint,5,opt,name=total_limit,json=totalLimit,proto3" json:"total_limit,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendPool) Reset() {
	*x = FriendPool{}
	mi := &file_pool_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendPool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendPool) ProtoMessage() {}

func (x *FriendPool) ProtoReflect() protoreflect.Message {
	mi := &file_pool_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendPool.ProtoReflect.Descriptor instead.
func (*FriendPool) Descriptor() ([]byte, []int) {
	return file_pool_proto_rawDescGZIP(), []int{11}
}

func (x *FriendPool) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FriendPool) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *FriendPool) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FriendPool) GetPoolMode() string {
	if x != nil {
		return x.PoolMode
	}
	return ""
}

func (x *FriendPool) GetTotalLimit() int64 {
	if x != nil {
		return x.TotalLimit
	}
	return 0
}

func (x *FriendPool) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type PoolList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pools         []*FriendPool          `protobuf:"bytes,1,rep,name=pools,proto3" json:"pools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolList) Reset() {
	*x = PoolList{}
	mi := &file_pool_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolList) ProtoMessage() {}

func (x *PoolList) ProtoReflect() protoreflect.Message {
	mi := &file_pool_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolList.ProtoReflect.Descriptor instead.
func (*PoolList) Descriptor() ([]byte, []int) {
	return file_pool_proto_rawDescGZIP(), []int{12}
}

func (x *PoolList) GetPools() []*FriendPool {
	if x != nil {
		return x.Pools
	}
	return nil
}

type PoolMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolId        string                 `protobuf:"bytes,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	ProfileId     string                 `protobuf:"bytes,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	ProfileName   string                 `protobuf:"bytes,3,opt,name=profile_name,json=profileName,proto3" json:"profile_name,omitempty"`
	JoinedAt      int64                  `protobuf:"varint,4,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolMember) Reset() {
	*x = PoolMember{}
	mi := &file_pool_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolMember) ProtoMessage() {}

func (x *PoolMember) ProtoReflect() protoreflect.Message {
	mi := &file_pool_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolMember.ProtoReflect.Descriptor instead.
func (*PoolMember) Descriptor() ([]byte, []int) {
	return file_pool_proto_rawDescGZIP(), []int{13}
}

func (x *PoolMember) GetPoolId() string {
	if x != nil {
		return x.PoolId
	}
	return ""
}

func (x *PoolMember) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *PoolMember) GetProfileName() string {
	if x != nil {
		return x.ProfileName
	}
	return ""
}

func (x *PoolMember) GetJoinedAt() int64 {
	if x != nil {
		return x.JoinedAt
	}
	return 0
}

type PoolMemberList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*PoolMember          `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolMemberList) Reset() {
	*x = PoolMemberList{}
	mi := &file_pool_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolMemberList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolMemberList) ProtoMessage() {}

func (x *PoolMemberList) ProtoReflect() protoreflect.Message {
	mi := &file_pool_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolMemberList.ProtoReflect.Descriptor instead.
func (*PoolMemberList) Descriptor() ([]byte, []int) {
	return file_pool_proto_rawDescGZIP(), []int{14}
}

func (x *PoolMemberList) GetMembers() []*PoolMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type PoolBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolId        string                 `protobuf:"bytes,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolBlock) Reset() {
	*x = PoolBlock{}
	mi := &file_pool_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolBlock) ProtoMessage() {}

func (x *PoolBlock) ProtoReflect() protoreflect.Message {
	mi := &file_pool_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolBlock.ProtoReflect.Descriptor instead.
func (*PoolBlock) Descriptor() ([]byte, []int) {
	return file_pool_proto_rawDescGZIP(), []int{15}
}

func (x *PoolBlock) GetPoolId() string {
	if x != nil {
		return x.PoolId
	}
	return ""
}

func (x *PoolBlock) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type PoolBlockList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocks        []*PoolBlock           `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolBlockList) Reset() {
	*x = PoolBlockList{}
	mi := &file_pool_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolBlockList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolBlockList) ProtoMessage() {}

func (x *PoolBlockList) ProtoReflect() protoreflect.Message {
	mi := &file_pool_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolBlockList.ProtoReflect.Descriptor instead.
func (*PoolBlockList) Descriptor() ([]byte, []int) {
	return file_pool_proto_rawDescGZIP(), []int{16}
}

func (x *PoolBlockList) GetBlocks() []*PoolBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type CreditsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Remaining     int64                  `protobuf:"varint,1,opt,name=remaining,proto3" json:"remaining,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreditsResponse) Reset() {
	*x = CreditsResponse{}
	mi := &file_pool_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditsResponse) ProtoMessage() {}

func (x *CreditsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pool_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditsResponse.ProtoReflect.Descriptor instead.
func (*CreditsResponse) Descriptor() ([]byte, []int) {
	return file_pool_proto_rawDescGZIP(), []int{17}
}

func (x *CreditsResponse) GetRemaining() int64 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *CreditsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_pool_proto protoreflect.FileDescriptor

const file_pool_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"pool.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\"+\n" +
	"\x10ListPoolsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"~\n" +
	"\x11CreatePoolRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tpool_mode\x18\x03 \x01(\tR\bpoolMode\x12\x1f\n" +
	"\vtotal_limit\x18\x04 \x01(\x03R\n" +
	"totalLimit\")\n" +
	"\x0eGetPoolRequest\x12\x17\n" +
	"\apool_id\x18\x01 \x01(\tR\x06poolId\"E\n" +
	"\x11DeletePoolRequest\x12\x17\n" +
	"\apool_id\x18\x01 \x01(\tR\x06poolId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"I\n" +
	"\x0fJoinPoolRequest\x12\x17\n" +
	"\apool_id\x18\x01 \x01(\tR\x06poolId\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\tR\tprofileId\"J\n" +
	"\x10LeavePoolRequest\x12\x17\n" +
	"\apool_id\x18\x01 \x01(\tR\x06poolId\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\tR\tprofileId\"-\n" +
	"\x12ListMembersRequest\x12\x17\n" +
	"\apool_id\x18\x01 \x01(\tR\x06poolId\"0\n" +
	"\x15ListPoolBlocksRequest\x12\x17\n" +
	"\apool_id\x18\x01 \x01(\tR\x06poolId\"O\n" +
	"\x18BlockPoolCategoryRequest\x12\x17\n" +
	"\apool_id\x18\x01 \x01(\tR\x06poolId\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\"Q\n" +
	"\x1aUnblockPoolCategoryRequest\x12\x17\n" +
	"\apool_id\x18\x01 \x01(\tR\x06poolId\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\"K\n" +
	"\x11GetCreditsRequest\x12\x17\n" +
	"\apool_id\x18\x01 \x01(\tR\x06poolId\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\tR\tprofileId\"\xac\x01\n" +
	"\n" +
	"FriendPool\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_by\x18\x02 \x01(\tR\tcreatedBy\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\tpool_mode\x18\x04 \x01(\tR\bpoolMode\x12\x1f\n" +
	"\vtotal_limit\x18\x05 \x01(\x03R\n" +
	"totalLimit\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\"3\n" +
	"\bPoolList\x12'\n" +
	"\x05pools\x18\x01 \x03(\v2\x11.proto.FriendPoolR\x05pools\"\x84\x01\n" +
	"\n" +
	"PoolMember\x12\x17\n" +
	"\apool_id\x18\x01 \x01(\tR\x06poolId\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\tR\tprofileId\x12!\n" +
	"\fprofile_name\x18\x03 \x01(\tR\vprofileName\x12\x1b\n" +
	"\tjoined_at\x18\x04 \x01(\x03R\bjoinedAt\"=\n" +
	"\x0ePoolMemberList\x12+\n" +
	"\amembers\x18\x01 \x03(\v2\x11.proto.PoolMemberR\amembers\"@\n" +
	"\tPoolBlock\x12\x17\n" +
	"\apool_id\x18\x01 \x01(\tR\x06poolId\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\"9\n" +
	"\rPoolBlockList\x12(\n" +
	"\x06blocks\x18\x01 \x03(\v2\x10.proto.PoolBlockR\x06blocks\"E\n" +
	"\x0fCreditsResponse\x12\x1c\n" +
	"\tremaining\x18\x01 \x01(\x03R\tremaining\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\xc9\x05\n" +
	"\vPoolService\x125\n" +
	"\tListPools\x12\x17.proto.ListPoolsRequest\x1a\x0f.proto.PoolList\x129\n" +
	"\n" +
	"CreatePool\x12\x18.proto.CreatePoolRequest\x1a\x11.proto.FriendPool\x123\n" +
	"\aGetPool\x12\x15.proto.GetPoolRequest\x1a\x11.proto.FriendPool\x12>\n" +
	"\n" +
	"DeletePool\x12\x18.proto.DeletePoolRequest\x1a\x16.google.protobuf.Empty\x12:\n" +
	"\bJoinPool\x12\x16.proto.JoinPoolRequest\x1a\x16.google.protobuf.Empty\x12<\n" +
	"\tLeavePool\x12\x17.proto.LeavePoolRequest\x1a\x16.google.protobuf.Empty\x12?\n" +
	"\vListMembers\x12\x19.proto.ListMembersRequest\x1a\x15.proto.PoolMemberList\x12@\n" +
	"\n" +
	"ListBlocks\x12\x1c.proto.ListPoolBlocksRequest\x1a\x14.proto.PoolBlockList\x12H\n" +
	"\rBlockCategory\x12\x1f.proto.BlockPoolCategoryRequest\x1a\x16.google.protobuf.Empty\x12L\n" +
	"\x0fUnblockCategory\x12!.proto.UnblockPoolCategoryRequest\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\n" +
	"GetCredits\x12\x18.proto.GetCreditsRequest\x1a\x16.proto.CreditsResponseB-Z+codeberg.org/will-x86/bdns/api/pkg/proto/pbb\x06proto3"

var (
	file_pool_proto_rawDescOnce sync.Once
	file_pool_proto_rawDescData []byte
)

func file_pool_proto_rawDescGZIP() []byte {
	file_pool_proto_rawDescOnce.Do(func() {
		file_pool_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pool_proto_rawDesc), len(file_pool_proto_rawDesc)))
	})
	return file_pool_proto_rawDescData
}

var file_pool_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_pool_proto_goTypes = []any{
	(*ListPoolsRequest)(nil),           // 0: proto.ListPoolsRequest
	(*CreatePoolRequest)(nil),          // 1: proto.CreatePoolRequest
	(*GetPoolRequest)(nil),             // 2: proto.GetPoolRequest
	(*DeletePoolRequest)(nil),          // 3: proto.DeletePoolRequest
	(*JoinPoolRequest)(nil),            // 4: proto.JoinPoolRequest
	(*LeavePoolRequest)(nil),           // 5: proto.LeavePoolRequest
	(*ListMembersRequest)(nil),         // 6: proto.ListMembersRequest
	(*ListPoolBlocksRequest)(nil),      // 7: proto.ListPoolBlocksRequest
	(*BlockPoolCategoryRequest)(nil),   // 8: proto.BlockPoolCategoryRequest
	(*UnblockPoolCategoryRequest)(nil), // 9: proto.UnblockPoolCategoryRequest
	(*GetCreditsRequest)(nil),          // 10: proto.GetCreditsRequest
	(*FriendPool)(nil),                 // 11: proto.FriendPool
	(*PoolList)(nil),                   // 12: proto.PoolList
	(*PoolMember)(nil),                 // 13: proto.PoolMember
	(*PoolMemberList)(nil),             // 14: proto.PoolMemberList
	(*PoolBlock)(nil),                  // 15: proto.PoolBlock
	(*PoolBlockList)(nil),              // 16: proto.PoolBlockList
	(*CreditsResponse)(nil),            // 17: proto.CreditsResponse
	(*emptypb.Empty)(nil),              // 18: google.protobuf.Empty
}
var file_pool_proto_depIdxs = []int32{
	11, // 0: proto.PoolList.pools:type_name -> proto.FriendPool
	13, // 1: proto.PoolMemberList.members:type_name -> proto.PoolMember
	15, // 2: proto.PoolBlockList.blocks:type_name -> proto.PoolBlock
	0,  // 3: proto.PoolService.ListPools:input_type -> proto.ListPoolsRequest
	1,  // 4: proto.PoolService.CreatePool:input_type -> proto.CreatePoolRequest
	2,  // 5: proto.PoolService.GetPool:input_type -> proto.GetPoolRequest
	3,  // 6: proto.PoolService.DeletePool:input_type -> proto.DeletePoolRequest
	4,  // 7: proto.PoolService.JoinPool:input_type -> proto.JoinPoolRequest
	5,  // 8: proto.PoolService.LeavePool:input_type -> proto.LeavePoolRequest
	6,  // 9: proto.PoolService.ListMembers:input_type -> proto.ListMembersRequest
	7,  // 10: proto.PoolService.ListBlocks:input_type -> proto.ListPoolBlocksRequest
	8,  // 11: proto.PoolService.BlockCategory:input_type -> proto.BlockPoolCategoryRequest
	9,  // 12: proto.PoolService.UnblockCategory:input_type -> proto.UnblockPoolCategoryRequest
	10, // 13: proto.PoolService.GetCredits:input_type -> proto.GetCreditsRequest
	12, // 14: proto.PoolService.ListPools:output_type -> proto.PoolList
	11, // 15: proto.PoolService.CreatePool:output_type -> proto.FriendPool
	11, // 16: proto.PoolService.GetPool:output_type -> proto.FriendPool
	18, // 17: proto.PoolService.DeletePool:output_type -> google.protobuf.Empty
	18, // 18: proto.PoolService.JoinPool:output_type -> google.protobuf.Empty
	18, // 19: proto.PoolService.LeavePool:output_type -> google.protobuf.Empty
	14, // 20: proto.PoolService.ListMembers:output_type -> proto.PoolMemberList
	16, // 21: proto.PoolService.ListBlocks:output_type -> proto.PoolBlockList
	18, // 22: proto.PoolService.BlockCategory:output_type -> google.protobuf.Empty
	18, // 23: proto.PoolService.UnblockCategory:output_type -> google.protobuf.Empty
	17, // 24: proto.PoolService.GetCredits:output_type -> proto.CreditsResponse
	14, // [14:25] is the sub-list for method output_type
	3,  // [3:14] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_pool_proto_init() }
func file_pool_proto_init() {
	if File_pool_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pool_proto_rawDesc), len(file_pool_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pool_proto_goTypes,
		DependencyIndexes: file_pool_proto_depIdxs,
		MessageInfos:      file_pool_proto_msgTypes,
	}.Build()
	File_pool_proto = out.File
	file_pool_proto_goTypes = nil
	file_pool_proto_depIdxs = nil
}
