// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: pool.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PoolService_ListPools_FullMethodName       = "/proto.PoolService/ListPools"
	PoolService_CreatePool_FullMethodName      = "/proto.PoolService/CreatePool"
	PoolService_GetPool_FullMethodName         = "/proto.PoolService/GetPool"
	PoolService_DeletePool_FullMethodName      = "/proto.PoolService/DeletePool"
	PoolService_JoinPool_FullMethodName        = "/proto.PoolService/JoinPool"
	PoolService_LeavePool_FullMethodName       = "/proto.PoolService/LeavePool"
	PoolService_ListMembers_FullMethodName     = "/proto.PoolService/ListMembers"
	PoolService_ListBlocks_FullMethodName      = "/proto.PoolService/ListBlocks"
	PoolService_BlockCategory_FullMethodName   = "/proto.PoolService/BlockCategory"
	PoolService_UnblockCategory_FullMethodName = "/proto.PoolService/UnblockCategory"
	PoolService_GetCredits_FullMethodName      = "/proto.PoolService/GetCredits"
)

// PoolServiceClient is the client API for PoolService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PoolServiceClient interface {
	ListPools(ctx context.Context, in *ListPoolsRequest, opts ...grpc.CallOption) (*PoolList, error)
	CreatePool(ctx context.Context, in *CreatePoolRequest, opts ...grpc.CallOption) (*FriendPool, error)
	GetPool(ctx context.Context, in *GetPoolRequest, opts ...grpc.CallOption) (*FriendPool, error)
	DeletePool(ctx context.Context, in *DeletePoolRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	JoinPool(ctx context.Context, in *JoinPoolRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	LeavePool(ctx context.Context, in *LeavePoolRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListMembers(ctx context.Context, in *ListMembersRequest, opts ...grpc.CallOption) (*PoolMemberList, error)
	ListBlocks(ctx context.Context, in *ListPoolBlocksRequest, opts ...grpc.CallOption) (*PoolBlockList, error)
	BlockCategory(ctx context.Context, in *BlockPoolCategoryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UnblockCategory(ctx context.Context, in *UnblockPoolCategoryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetCredits(ctx context.Context, in *GetCreditsRequest, opts ...grpc.CallOption) (*CreditsResponse, error)
}

type poolServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPoolServiceClient(cc grpc.ClientConnInterface) PoolServiceClient {
	return &poolServiceClient{cc}
}

func (c *poolServiceClient) ListPools(ctx context.Context, in *ListPoolsRequest, opts ...grpc.CallOption) (*PoolList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PoolList)
	err := c.cc.Invoke(ctx, PoolService_ListPools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolServiceClient) CreatePool(ctx context.Context, in *CreatePoolRequest, opts ...grpc.CallOption) (*FriendPool, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FriendPool)
	err := c.cc.Invoke(ctx, PoolService_CreatePool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolServiceClient) GetPool(ctx context.Context, in *GetPoolRequest, opts ...grpc.CallOption) (*FriendPool, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FriendPool)
	err := c.cc.Invoke(ctx, PoolService_GetPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolServiceClient) DeletePool(ctx context.Context, in *DeletePoolRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PoolService_DeletePool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolServiceClient) JoinPool(ctx context.Context, in *JoinPoolRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PoolService_JoinPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolServiceClient) LeavePool(ctx context.Context, in *LeavePoolRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PoolService_LeavePool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolServiceClient) ListMembers(ctx context.Context, in *ListMembersRequest, opts ...grpc.CallOption) (*PoolMemberList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PoolMemberList)
	err := c.cc.Invoke(ctx, PoolService_ListMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolServiceClient) ListBlocks(ctx context.Context, in *ListPoolBlocksRequest, opts ...grpc.CallOption) (*PoolBlockList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PoolBlockList)
	err := c.cc.Invoke(ctx, PoolService_ListBlocks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolServiceClient) BlockCategory(ctx context.Context, in *BlockPoolCategoryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PoolService_BlockCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolServiceClient) UnblockCategory(ctx context.Context, in *UnblockPoolCategoryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PoolService_UnblockCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolServiceClient) GetCredits(ctx context.Context, in *GetCreditsRequest, opts ...grpc.CallOption) (*CreditsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreditsResponse)
	err := c.cc.Invoke(ctx, PoolService_GetCredits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PoolServiceServer is the server API for PoolService service.
// All implementations must embed UnimplementedPoolServiceServer
// for forward compatibility.
type PoolServiceServer interface {
	ListPools(context.Context, *ListPoolsRequest) (*PoolList, error)
	CreatePool(context.Context, *CreatePoolRequest) (*FriendPool, error)
	GetPool(context.Context, *GetPoolRequest) (*FriendPool, error)
	DeletePool(context.Context, *DeletePoolRequest) (*emptypb.Empty, error)
	JoinPool(context.Context, *JoinPoolRequest) (*emptypb.Empty, error)
	LeavePool(context.Context, *LeavePoolRequest) (*emptypb.Empty, error)
	ListMembers(context.Context, *ListMembersRequest) (*PoolMemberList, error)
	ListBlocks(context.Context, *ListPoolBlocksRequest) (*PoolBlockList, error)
	BlockCategory(context.Context, *BlockPoolCategoryRequest) (*emptypb.Empty, error)
	UnblockCategory(context.Context, *UnblockPoolCategoryRequest) (*emptypb.Empty, error)
	GetCredits(context.Context, *GetCreditsRequest) (*CreditsResponse, error)
	mustEmbedUnimplementedPoolServiceServer()
}

// UnimplementedPoolServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPoolServiceServer struct{}

func (UnimplementedPoolServiceServer) ListPools(context.Context, *ListPoolsRequest) (*PoolList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPools not implemented")
}
func (UnimplementedPoolServiceServer) CreatePool(context.Context, *CreatePoolRequest) (*FriendPool, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePool not implemented")
}
func (UnimplementedPoolServiceServer) GetPool(context.Context, *GetPoolRequest) (*FriendPool, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPool not implemented")
}
func (UnimplementedPoolServiceServer) DeletePool(context.Context, *DeletePoolRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePool not implemented")
}
func (UnimplementedPoolServiceServer) JoinPool(context.Context, *JoinPoolRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinPool not implemented")
}
func (UnimplementedPoolServiceServer) LeavePool(context.Context, *LeavePoolRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method LeavePool not implemented")
}
func (UnimplementedPoolServiceServer) ListMembers(context.Context, *ListMembersRequest) (*PoolMemberList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMembers not implemented")
}
func (UnimplementedPoolServiceServer) ListBlocks(context.Context, *ListPoolBlocksRequest) (*PoolBlockList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBlocks not implemented")
}
func (UnimplementedPoolServiceServer) BlockCategory(context.Context, *BlockPoolCategoryRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method BlockCategory not implemented")
}
func (UnimplementedPoolServiceServer) UnblockCategory(context.Context, *UnblockPoolCategoryRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UnblockCategory not implemented")
}
func (UnimplementedPoolServiceServer) GetCredits(context.Context, *GetCreditsRequest) (*CreditsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCredits not implemented")
}
func (UnimplementedPoolServiceServer) mustEmbedUnimplementedPoolServiceServer() {}
func (UnimplementedPoolServiceServer) testEmbeddedByValue()                     {}

// UnsafePoolServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PoolServiceServer will
// result in compilation errors.
type UnsafePoolServiceServer interface {
	mustEmbedUnimplementedPoolServiceServer()
}

func RegisterPoolServiceServer(s grpc.ServiceRegistrar, srv PoolServiceServer) {
	// If the following call panics, it indicates UnimplementedPoolServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PoolService_ServiceDesc, srv)
}

func _PoolService_ListPools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPoolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolServiceServer).ListPools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolService_ListPools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolServiceServer).ListPools(ctx, req.(*ListPoolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolService_CreatePool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolServiceServer).CreatePool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolService_CreatePool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolServiceServer).CreatePool(ctx, req.(*CreatePoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolService_GetPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolServiceServer).GetPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolService_GetPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolServiceServer).GetPool(ctx, req.(*GetPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolService_DeletePool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolServiceServer).DeletePool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolService_DeletePool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolServiceServer).DeletePool(ctx, req.(*DeletePoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolService_JoinPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolServiceServer).JoinPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolService_JoinPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolServiceServer).JoinPool(ctx, req.(*JoinPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolService_LeavePool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeavePoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolServiceServer).LeavePool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolService_LeavePool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolServiceServer).LeavePool(ctx, req.(*LeavePoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolService_ListMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolServiceServer).ListMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolService_ListMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolServiceServer).ListMembers(ctx, req.(*ListMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolService_ListBlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPoolBlocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolServiceServer).ListBlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolService_ListBlocks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolServiceServer).ListBlocks(ctx, req.(*ListPoolBlocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolService_BlockCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockPoolCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolServiceServer).BlockCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolService_BlockCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolServiceServer).BlockCategory(ctx, req.(*BlockPoolCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolService_UnblockCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnblockPoolCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolServiceServer).UnblockCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolService_UnblockCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolServiceServer).UnblockCategory(ctx, req.(*UnblockPoolCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolService_GetCredits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCreditsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolServiceServer).GetCredits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolService_GetCredits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolServiceServer).GetCredits(ctx, req.(*GetCreditsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PoolService_ServiceDesc is the grpc.ServiceDesc for PoolService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PoolService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PoolService",
	HandlerType: (*PoolServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPools",
			Handler:    _PoolService_ListPools_Handler,
		},
		{
			MethodName: "CreatePool",
			Handler:    _PoolService_CreatePool_Handler,
		},
		{
			MethodName: "GetPool",
			Handler:    _PoolService_GetPool_Handler,
		},
		{
			MethodName: "DeletePool",
			Handler:    _PoolService_DeletePool_Handler,
		},
		{
			MethodName: "JoinPool",
			Handler:    _PoolService_JoinPool_Handler,
		},
		{
			MethodName: "LeavePool",
			Handler:    _PoolService_LeavePool_Handler,
		},
		{
			MethodName: "ListMembers",
			Handler:    _PoolService_ListMembers_Handler,
		},
		{
			MethodName: "ListBlocks",
			Handler:    _PoolService_ListBlocks_Handler,
		},
		{
			MethodName: "BlockCategory",
			Handler:    _PoolService_BlockCategory_Handler,
		},
		{
			MethodName: "UnblockCategory",
			Handler:    _PoolService_UnblockCategory_Handler,
		},
		{
			MethodName: "GetCredits",
			Handler:    _PoolService_GetCredits_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pool.proto",
}
