// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: timeblock.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TimeBlockService_List_FullMethodName   = "/proto.TimeBlockService/List"
	TimeBlockService_Create_FullMethodName = "/proto.TimeBlockService/Create"
	TimeBlockService_Delete_FullMethodName = "/proto.TimeBlockService/Delete"
)

// TimeBlockServiceClient is the client API for TimeBlockService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TimeBlockServiceClient interface {
	List(ctx context.Context, in *ListTimeBlocksRequest, opts ...grpc.CallOption) (*TimeBlockList, error)
	Create(ctx context.Context, in *CreateTimeBlockRequest, opts ...grpc.CallOption) (*TimeBlock, error)
	Delete(ctx context.Context, in *DeleteTimeBlockRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type timeBlockServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTimeBlockServiceClient(cc grpc.ClientConnInterface) TimeBlockServiceClient {
	return &timeBlockServiceClient{cc}
}

func (c *timeBlockServiceClient) List(ctx context.Context, in *ListTimeBlocksRequest, opts ...grpc.CallOption) (*TimeBlockList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TimeBlockList)
	err := c.cc.Invoke(ctx, TimeBlockService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeBlockServiceClient) Create(ctx context.Context, in *CreateTimeBlockRequest, opts ...grpc.CallOption) (*TimeBlock, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TimeBlock)
	err := c.cc.Invoke(ctx, TimeBlockService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeBlockServiceClient) Delete(ctx context.Context, in *DeleteTimeBlockRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TimeBlockService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TimeBlockServiceServer is the server API for TimeBlockService service.
// All implementations must embed UnimplementedTimeBlockServiceServer
// for forward compatibility.
type TimeBlockServiceServer interface {
	List(context.Context, *ListTimeBlocksRequest) (*TimeBlockList, error)
	Create(context.Context, *CreateTimeBlockRequest) (*TimeBlock, error)
	Delete(context.Context, *DeleteTimeBlockRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedTimeBlockServiceServer()
}

// UnimplementedTimeBlockServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTimeBlockServiceServer struct{}

func (UnimplementedTimeBlockServiceServer) List(context.Context, *ListTimeBlocksRequest) (*TimeBlockList, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedTimeBlockServiceServer) Create(context.Context, *CreateTimeBlockRequest) (*TimeBlock, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedTimeBlockServiceServer) Delete(context.Context, *DeleteTimeBlockRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedTimeBlockServiceServer) mustEmbedUnimplementedTimeBlockServiceServer() {}
func (UnimplementedTimeBlockServiceServer) testEmbeddedByValue()                          {}

// UnsafeTimeBlockServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TimeBlockServiceServer will
// result in compilation errors.
type UnsafeTimeBlockServiceServer interface {
	mustEmbedUnimplementedTimeBlockServiceServer()
}

func RegisterTimeBlockServiceServer(s grpc.ServiceRegistrar, srv TimeBlockServiceServer) {
	// If the following call panics, it indicates UnimplementedTimeBlockServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TimeBlockService_ServiceDesc, srv)
}

func _TimeBlockService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTimeBlocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeBlockServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimeBlockService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeBlockServiceServer).List(ctx, req.(*ListTimeBlocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimeBlockService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTimeBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeBlockServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimeBlockService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeBlockServiceServer).Create(ctx, req.(*CreateTimeBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimeBlockService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTimeBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeBlockServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimeBlockService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeBlockServiceServer).Delete(ctx, req.(*DeleteTimeBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TimeBlockService_ServiceDesc is the grpc.ServiceDesc for TimeBlockService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TimeBlockService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TimeBlockService",
	HandlerType: (*TimeBlockServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _TimeBlockService_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _TimeBlockService_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _TimeBlockService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "timeblock.proto",
}
