// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: timeblock.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListTimeBlocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTimeBlocksRequest) Reset() {
	*x = ListTimeBlocksRequest{}
	mi := &file_timeblock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTimeBlocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTimeBlocksRequest) ProtoMessage() {}

func (x *ListTimeBlocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_timeblock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTimeBlocksRequest.ProtoReflect.Descriptor instead.
func (*ListTimeBlocksRequest) Descriptor() ([]byte, []int) {
	return file_timeblock_proto_rawDescGZIP(), []int{0}
}

func (x *ListTimeBlocksRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

type CreateTimeBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	StartTime     int32                  `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int32                  `protobuf:"varint,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Day           int32                  `protobuf:"varint,5,opt,name=day,proto3" json:"day,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTimeBlockRequest) Reset() {
	*x = CreateTimeBlockRequest{}
	mi := &file_timeblock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTimeBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTimeBlockRequest) ProtoMessage() {}

func (x *CreateTimeBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_timeblock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTimeBlockRequest.ProtoReflect.Descriptor instead.
func (*CreateTimeBlockRequest) Descriptor() ([]byte, []int) {
	return file_timeblock_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTimeBlockRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *CreateTimeBlockRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateTimeBlockRequest) GetStartTime() int32 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *CreateTimeBlockRequest) GetEndTime() int32 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *CreateTimeBlockRequest) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

type DeleteTimeBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockId       string                 `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTimeBlockRequest) Reset() {
	*x = DeleteTimeBlockRequest{}
	mi := &file_timeblock_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTimeBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTimeBlockRequest) ProtoMessage() {}

func (x *DeleteTimeBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_timeblock_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTimeBlockRequest.ProtoReflect.Descriptor instead.
func (*DeleteTimeBlockRequest) Descriptor() ([]byte, []int) {
	return file_timeblock_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteTimeBlockRequest) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

type TimeBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProfileId     string                 `protobuf:"bytes,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	StartTime     int32                  `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int32                  `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Day           int32                  `protobuf:"varint,6,opt,name=day,proto3" json:"day,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeBlock) Reset() {
	*x = TimeBlock{}
	mi := &file_timeblock_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeBlock) ProtoMessage() {}

func (x *TimeBlock) ProtoReflect() protoreflect.Message {
	mi := &file_timeblock_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeBlock.ProtoReflect.Descriptor instead.
func (*TimeBlock) Descriptor() ([]byte, []int) {
	return file_timeblock_proto_rawDescGZIP(), []int{3}
}

func (x *TimeBlock) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TimeBlock) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *TimeBlock) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *TimeBlock) GetStartTime() int32 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *TimeBlock) GetEndTime() int32 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *TimeBlock) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *TimeBlock) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type TimeBlockList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocks        []*TimeBlock           `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeBlockList) Reset() {
	*x = TimeBlockList{}
	mi := &file_timeblock_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeBlockList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeBlockList) ProtoMessage() {}

func (x *TimeBlockList) ProtoReflect() protoreflect.Message {
	mi := &file_timeblock_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeBlockList.ProtoReflect.Descriptor instead.
func (*TimeBlockList) Descriptor() ([]byte, []int) {
	return file_timeblock_proto_rawDescGZIP(), []int{4}
}

func (x *TimeBlockList) GetBlocks() []*TimeBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

var File_timeblock_proto protoreflect.FileDescriptor

const file_timeblock_proto_rawDesc = "" +
	"\n" +
	"\x0ftimeblock.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\"6\n" +
	"\x15ListTimeBlocksRequest\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\"\x9f\x01\n" +
	"\x16CreateTimeBlockRequest\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\x05R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\x05R\aendTime\x12\x10\n" +
	"\x03day\x18\x05 \x01(\x05R\x03day\"3\n" +
	"\x16DeleteTimeBlockRequest\x12\x19\n" +
	"\bblock_id\x18\x01 \x01(\tR\ablockId\"\xc1\x01\n" +
	"\tTimeBlock\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\tR\tprofileId\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\x05R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\x05R\aendTime\x12\x10\n" +
	"\x03day\x18\x06 \x01(\x05R\x03day\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\"9\n" +
	"\rTimeBlockList\x12(\n" +
	"\x06blocks\x18\x01 \x03(\v2\x10.proto.TimeBlockR\x06blocks2\xca\x01\n" +
	"\x10TimeBlockService\x12:\n" +
	"\x04List\x12\x1c.proto.ListTimeBlocksRequest\x1a\x14.proto.TimeBlockList\x129\n" +
	"\x06Create\x12\x1d.proto.CreateTimeBlockRequest\x1a\x10.proto.TimeBlock\x12?\n" +
	"\x06Delete\x12\x1d.proto.DeleteTimeBlockRequest\x1a\x16.google.protobuf.EmptyB*Z(codeberg.org/will-x86/bdns/api/pkg/protob\x06proto3"

var (
	file_timeblock_proto_rawDescOnce sync.Once
	file_timeblock_proto_rawDescData []byte
)

func file_timeblock_proto_rawDescGZIP() []byte {
	file_timeblock_proto_rawDescOnce.Do(func() {
		file_timeblock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_timeblock_proto_rawDesc), len(file_timeblock_proto_rawDesc)))
	})
	return file_timeblock_proto_rawDescData
}

var file_timeblock_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_timeblock_proto_goTypes = []any{
	(*ListTimeBlocksRequest)(nil),  // 0: proto.ListTimeBlocksRequest
	(*CreateTimeBlockRequest)(nil), // 1: proto.CreateTimeBlockRequest
	(*DeleteTimeBlockRequest)(nil), // 2: proto.DeleteTimeBlockRequest
	(*TimeBlock)(nil),              // 3: proto.TimeBlock
	(*TimeBlockList)(nil),          // 4: proto.TimeBlockList
	(*emptypb.Empty)(nil),          // 5: google.protobuf.Empty
}
var file_timeblock_proto_depIdxs = []int32{
	3, // 0: proto.TimeBlockList.blocks:type_name -> proto.TimeBlock
	0, // 1: proto.TimeBlockService.List:input_type -> proto.ListTimeBlocksRequest
	1, // 2: proto.TimeBlockService.Create:input_type -> proto.CreateTimeBlockRequest
	2, // 3: proto.TimeBlockService.Delete:input_type -> proto.DeleteTimeBlockRequest
	4, // 4: proto.TimeBlockService.List:output_type -> proto.TimeBlockList
	3, // 5: proto.TimeBlockService.Create:output_type -> proto.TimeBlock
	5, // 6: proto.TimeBlockService.Delete:output_type -> google.protobuf.Empty
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_timeblock_proto_init() }
func file_timeblock_proto_init() {
	if File_timeblock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_timeblock_proto_rawDesc), len(file_timeblock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_timeblock_proto_goTypes,
		DependencyIndexes: file_timeblock_proto_depIdxs,
		MessageInfos:      file_timeblock_proto_msgTypes,
	}.Build()
	File_timeblock_proto = out.File
	file_timeblock_proto_goTypes = nil
	file_timeblock_proto_depIdxs = nil
}
