// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.5
// source: whitelist.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WhitelistService_ListPermanent_FullMethodName   = "/proto.WhitelistService/ListPermanent"
	WhitelistService_AddPermanent_FullMethodName    = "/proto.WhitelistService/AddPermanent"
	WhitelistService_RemovePermanent_FullMethodName = "/proto.WhitelistService/RemovePermanent"
	WhitelistService_ListTemporary_FullMethodName   = "/proto.WhitelistService/ListTemporary"
	WhitelistService_AddTemporary_FullMethodName    = "/proto.WhitelistService/AddTemporary"
	WhitelistService_RemoveTemporary_FullMethodName = "/proto.WhitelistService/RemoveTemporary"
)

// WhitelistServiceClient is the client API for WhitelistService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WhitelistServiceClient interface {
	ListPermanent(ctx context.Context, in *ListPermanentRequest, opts ...grpc.CallOption) (*WhitelistDomains, error)
	AddPermanent(ctx context.Context, in *AddPermanentRequest, opts ...grpc.CallOption) (*WhitelistDomain, error)
	RemovePermanent(ctx context.Context, in *RemovePermanentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListTemporary(ctx context.Context, in *ListTemporaryRequest, opts ...grpc.CallOption) (*WhitelistDomainsTemp, error)
	AddTemporary(ctx context.Context, in *AddTemporaryRequest, opts ...grpc.CallOption) (*WhitelistDomainTemp, error)
	RemoveTemporary(ctx context.Context, in *RemoveTemporaryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type whitelistServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWhitelistServiceClient(cc grpc.ClientConnInterface) WhitelistServiceClient {
	return &whitelistServiceClient{cc}
}

func (c *whitelistServiceClient) ListPermanent(ctx context.Context, in *ListPermanentRequest, opts ...grpc.CallOption) (*WhitelistDomains, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WhitelistDomains)
	err := c.cc.Invoke(ctx, WhitelistService_ListPermanent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whitelistServiceClient) AddPermanent(ctx context.Context, in *AddPermanentRequest, opts ...grpc.CallOption) (*WhitelistDomain, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WhitelistDomain)
	err := c.cc.Invoke(ctx, WhitelistService_AddPermanent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whitelistServiceClient) RemovePermanent(ctx context.Context, in *RemovePermanentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WhitelistService_RemovePermanent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whitelistServiceClient) ListTemporary(ctx context.Context, in *ListTemporaryRequest, opts ...grpc.CallOption) (*WhitelistDomainsTemp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WhitelistDomainsTemp)
	err := c.cc.Invoke(ctx, WhitelistService_ListTemporary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whitelistServiceClient) AddTemporary(ctx context.Context, in *AddTemporaryRequest, opts ...grpc.CallOption) (*WhitelistDomainTemp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WhitelistDomainTemp)
	err := c.cc.Invoke(ctx, WhitelistService_AddTemporary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whitelistServiceClient) RemoveTemporary(ctx context.Context, in *RemoveTemporaryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WhitelistService_RemoveTemporary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WhitelistServiceServer is the server API for WhitelistService service.
// All implementations must embed UnimplementedWhitelistServiceServer
// for forward compatibility.
type WhitelistServiceServer interface {
	ListPermanent(context.Context, *ListPermanentRequest) (*WhitelistDomains, error)
	AddPermanent(context.Context, *AddPermanentRequest) (*WhitelistDomain, error)
	RemovePermanent(context.Context, *RemovePermanentRequest) (*emptypb.Empty, error)
	ListTemporary(context.Context, *ListTemporaryRequest) (*WhitelistDomainsTemp, error)
	AddTemporary(context.Context, *AddTemporaryRequest) (*WhitelistDomainTemp, error)
	RemoveTemporary(context.Context, *RemoveTemporaryRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedWhitelistServiceServer()
}

// UnimplementedWhitelistServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWhitelistServiceServer struct{}

func (UnimplementedWhitelistServiceServer) ListPermanent(context.Context, *ListPermanentRequest) (*WhitelistDomains, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPermanent not implemented")
}
func (UnimplementedWhitelistServiceServer) AddPermanent(context.Context, *AddPermanentRequest) (*WhitelistDomain, error) {
	return nil, status.Error(codes.Unimplemented, "method AddPermanent not implemented")
}
func (UnimplementedWhitelistServiceServer) RemovePermanent(context.Context, *RemovePermanentRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemovePermanent not implemented")
}
func (UnimplementedWhitelistServiceServer) ListTemporary(context.Context, *ListTemporaryRequest) (*WhitelistDomainsTemp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTemporary not implemented")
}
func (UnimplementedWhitelistServiceServer) AddTemporary(context.Context, *AddTemporaryRequest) (*WhitelistDomainTemp, error) {
	return nil, status.Error(codes.Unimplemented, "method AddTemporary not implemented")
}
func (UnimplementedWhitelistServiceServer) RemoveTemporary(context.Context, *RemoveTemporaryRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveTemporary not implemented")
}
func (UnimplementedWhitelistServiceServer) mustEmbedUnimplementedWhitelistServiceServer() {}
func (UnimplementedWhitelistServiceServer) testEmbeddedByValue()                          {}

// UnsafeWhitelistServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WhitelistServiceServer will
// result in compilation errors.
type UnsafeWhitelistServiceServer interface {
	mustEmbedUnimplementedWhitelistServiceServer()
}

func RegisterWhitelistServiceServer(s grpc.ServiceRegistrar, srv WhitelistServiceServer) {
	// If the following call panics, it indicates UnimplementedWhitelistServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WhitelistService_ServiceDesc, srv)
}

func _WhitelistService_ListPermanent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPermanentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhitelistServiceServer).ListPermanent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhitelistService_ListPermanent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhitelistServiceServer).ListPermanent(ctx, req.(*ListPermanentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhitelistService_AddPermanent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPermanentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhitelistServiceServer).AddPermanent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhitelistService_AddPermanent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhitelistServiceServer).AddPermanent(ctx, req.(*AddPermanentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhitelistService_RemovePermanent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePermanentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhitelistServiceServer).RemovePermanent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhitelistService_RemovePermanent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhitelistServiceServer).RemovePermanent(ctx, req.(*RemovePermanentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhitelistService_ListTemporary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTemporaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhitelistServiceServer).ListTemporary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhitelistService_ListTemporary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhitelistServiceServer).ListTemporary(ctx, req.(*ListTemporaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhitelistService_AddTemporary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTemporaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhitelistServiceServer).AddTemporary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhitelistService_AddTemporary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhitelistServiceServer).AddTemporary(ctx, req.(*AddTemporaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhitelistService_RemoveTemporary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTemporaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhitelistServiceServer).RemoveTemporary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhitelistService_RemoveTemporary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhitelistServiceServer).RemoveTemporary(ctx, req.(*RemoveTemporaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WhitelistService_ServiceDesc is the grpc.ServiceDesc for WhitelistService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WhitelistService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.WhitelistService",
	HandlerType: (*WhitelistServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPermanent",
			Handler:    _WhitelistService_ListPermanent_Handler,
		},
		{
			MethodName: "AddPermanent",
			Handler:    _WhitelistService_AddPermanent_Handler,
		},
		{
			MethodName: "RemovePermanent",
			Handler:    _WhitelistService_RemovePermanent_Handler,
		},
		{
			MethodName: "ListTemporary",
			Handler:    _WhitelistService_ListTemporary_Handler,
		},
		{
			MethodName: "AddTemporary",
			Handler:    _WhitelistService_AddTemporary_Handler,
		},
		{
			MethodName: "RemoveTemporary",
			Handler:    _WhitelistService_RemoveTemporary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "whitelist.proto",
}
