// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: whitelist.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListPermanentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermanentRequest) Reset() {
	*x = ListPermanentRequest{}
	mi := &file_whitelist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermanentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermanentRequest) ProtoMessage() {}

func (x *ListPermanentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whitelist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermanentRequest.ProtoReflect.Descriptor instead.
func (*ListPermanentRequest) Descriptor() ([]byte, []int) {
	return file_whitelist_proto_rawDescGZIP(), []int{0}
}

func (x *ListPermanentRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

type AddPermanentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPermanentRequest) Reset() {
	*x = AddPermanentRequest{}
	mi := &file_whitelist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPermanentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPermanentRequest) ProtoMessage() {}

func (x *AddPermanentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whitelist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPermanentRequest.ProtoReflect.Descriptor instead.
func (*AddPermanentRequest) Descriptor() ([]byte, []int) {
	return file_whitelist_proto_rawDescGZIP(), []int{1}
}

func (x *AddPermanentRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *AddPermanentRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type RemovePermanentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePermanentRequest) Reset() {
	*x = RemovePermanentRequest{}
	mi := &file_whitelist_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePermanentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePermanentRequest) ProtoMessage() {}

func (x *RemovePermanentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whitelist_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePermanentRequest.ProtoReflect.Descriptor instead.
func (*RemovePermanentRequest) Descriptor() ([]byte, []int) {
	return file_whitelist_proto_rawDescGZIP(), []int{2}
}

func (x *RemovePermanentRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *RemovePermanentRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type ListTemporaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemporaryRequest) Reset() {
	*x = ListTemporaryRequest{}
	mi := &file_whitelist_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemporaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemporaryRequest) ProtoMessage() {}

func (x *ListTemporaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whitelist_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemporaryRequest.ProtoReflect.Descriptor instead.
func (*ListTemporaryRequest) Descriptor() ([]byte, []int) {
	return file_whitelist_proto_rawDescGZIP(), []int{3}
}

func (x *ListTemporaryRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

type AddTemporaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTemporaryRequest) Reset() {
	*x = AddTemporaryRequest{}
	mi := &file_whitelist_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTemporaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTemporaryRequest) ProtoMessage() {}

func (x *AddTemporaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whitelist_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTemporaryRequest.ProtoReflect.Descriptor instead.
func (*AddTemporaryRequest) Descriptor() ([]byte, []int) {
	return file_whitelist_proto_rawDescGZIP(), []int{4}
}

func (x *AddTemporaryRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *AddTemporaryRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *AddTemporaryRequest) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type RemoveTemporaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTemporaryRequest) Reset() {
	*x = RemoveTemporaryRequest{}
	mi := &file_whitelist_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTemporaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTemporaryRequest) ProtoMessage() {}

func (x *RemoveTemporaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whitelist_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTemporaryRequest.ProtoReflect.Descriptor instead.
func (*RemoveTemporaryRequest) Descriptor() ([]byte, []int) {
	return file_whitelist_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveTemporaryRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *RemoveTemporaryRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type WhitelistDomain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhitelistDomain) Reset() {
	*x = WhitelistDomain{}
	mi := &file_whitelist_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhitelistDomain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhitelistDomain) ProtoMessage() {}

func (x *WhitelistDomain) ProtoReflect() protoreflect.Message {
	mi := &file_whitelist_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhitelistDomain.ProtoReflect.Descriptor instead.
func (*WhitelistDomain) Descriptor() ([]byte, []int) {
	return file_whitelist_proto_rawDescGZIP(), []int{6}
}

func (x *WhitelistDomain) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type WhitelistDomains struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domains       []string               `protobuf:"bytes,1,rep,name=domains,proto3" json:"domains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhitelistDomains) Reset() {
	*x = WhitelistDomains{}
	mi := &file_whitelist_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhitelistDomains) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhitelistDomains) ProtoMessage() {}

func (x *WhitelistDomains) ProtoReflect() protoreflect.Message {
	mi := &file_whitelist_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhitelistDomains.ProtoReflect.Descriptor instead.
func (*WhitelistDomains) Descriptor() ([]byte, []int) {
	return file_whitelist_proto_rawDescGZIP(), []int{7}
}

func (x *WhitelistDomains) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

type WhitelistDomainTemp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhitelistDomainTemp) Reset() {
	*x = WhitelistDomainTemp{}
	mi := &file_whitelist_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhitelistDomainTemp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhitelistDomainTemp) ProtoMessage() {}

func (x *WhitelistDomainTemp) ProtoReflect() protoreflect.Message {
	mi := &file_whitelist_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhitelistDomainTemp.ProtoReflect.Descriptor instead.
func (*WhitelistDomainTemp) Descriptor() ([]byte, []int) {
	return file_whitelist_proto_rawDescGZIP(), []int{8}
}

func (x *WhitelistDomainTemp) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *WhitelistDomainTemp) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type WhitelistDomainsTemp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*WhitelistDomainTemp `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhitelistDomainsTemp) Reset() {
	*x = WhitelistDomainsTemp{}
	mi := &file_whitelist_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhitelistDomainsTemp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhitelistDomainsTemp) ProtoMessage() {}

func (x *WhitelistDomainsTemp) ProtoReflect() protoreflect.Message {
	mi := &file_whitelist_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhitelistDomainsTemp.ProtoReflect.Descriptor instead.
func (*WhitelistDomainsTemp) Descriptor() ([]byte, []int) {
	return file_whitelist_proto_rawDescGZIP(), []int{9}
}

func (x *WhitelistDomainsTemp) GetEntries() []*WhitelistDomainTemp {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_whitelist_proto protoreflect.FileDescriptor

const file_whitelist_proto_rawDesc = "" +
	"\n" +
	"\x0fwhitelist.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\"5\n" +
	"\x14ListPermanentRequest\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\"L\n" +
	"\x13AddPermanentRequest\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\"O\n" +
	"\x16RemovePermanentRequest\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\"5\n" +
	"\x14ListTemporaryRequest\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\"k\n" +
	"\x13AddTemporaryRequest\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\"O\n" +
	"\x16RemoveTemporaryRequest\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\")\n" +
	"\x0fWhitelistDomain\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\",\n" +
	"\x10WhitelistDomains\x12\x18\n" +
	"\adomains\x18\x01 \x03(\tR\adomains\"L\n" +
	"\x13WhitelistDomainTemp\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\"L\n" +
	"\x14WhitelistDomainsTemp\x124\n" +
	"\aentries\x18\x01 \x03(\v2\x1a.proto.WhitelistDomainTempR\aentries2\xc4\x03\n" +
	"\x10WhitelistService\x12E\n" +
	"\rListPermanent\x12\x1b.proto.ListPermanentRequest\x1a\x17.proto.WhitelistDomains\x12B\n" +
	"\fAddPermanent\x12\x1a.proto.AddPermanentRequest\x1a\x16.proto.WhitelistDomain\x12H\n" +
	"\x0fRemovePermanent\x12\x1d.proto.RemovePermanentRequest\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\rListTemporary\x12\x1b.proto.ListTemporaryRequest\x1a\x1b.proto.WhitelistDomainsTemp\x12F\n" +
	"\fAddTemporary\x12\x1a.proto.AddTemporaryRequest\x1a\x1a.proto.WhitelistDomainTemp\x12H\n" +
	"\x0fRemoveTemporary\x12\x1d.proto.RemoveTemporaryRequest\x1a\x16.google.protobuf.EmptyB-Z+codeberg.org/will-x86/bdns/api/pkg/proto/pbb\x06proto3"

var (
	file_whitelist_proto_rawDescOnce sync.Once
	file_whitelist_proto_rawDescData []byte
)

func file_whitelist_proto_rawDescGZIP() []byte {
	file_whitelist_proto_rawDescOnce.Do(func() {
		file_whitelist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_whitelist_proto_rawDesc), len(file_whitelist_proto_rawDesc)))
	})
	return file_whitelist_proto_rawDescData
}

var file_whitelist_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_whitelist_proto_goTypes = []any{
	(*ListPermanentRequest)(nil),   // 0: proto.ListPermanentRequest
	(*AddPermanentRequest)(nil),    // 1: proto.AddPermanentRequest
	(*RemovePermanentRequest)(nil), // 2: proto.RemovePermanentRequest
	(*ListTemporaryRequest)(nil),   // 3: proto.ListTemporaryRequest
	(*AddTemporaryRequest)(nil),    // 4: proto.AddTemporaryRequest
	(*RemoveTemporaryRequest)(nil), // 5: proto.RemoveTemporaryRequest
	(*WhitelistDomain)(nil),        // 6: proto.WhitelistDomain
	(*WhitelistDomains)(nil),       // 7: proto.WhitelistDomains
	(*WhitelistDomainTemp)(nil),    // 8: proto.WhitelistDomainTemp
	(*WhitelistDomainsTemp)(nil),   // 9: proto.WhitelistDomainsTemp
	(*emptypb.Empty)(nil),          // 10: google.protobuf.Empty
}
var file_whitelist_proto_depIdxs = []int32{
	8,  // 0: proto.WhitelistDomainsTemp.entries:type_name -> proto.WhitelistDomainTemp
	0,  // 1: proto.WhitelistService.ListPermanent:input_type -> proto.ListPermanentRequest
	1,  // 2: proto.WhitelistService.AddPermanent:input_type -> proto.AddPermanentRequest
	2,  // 3: proto.WhitelistService.RemovePermanent:input_type -> proto.RemovePermanentRequest
	3,  // 4: proto.WhitelistService.ListTemporary:input_type -> proto.ListTemporaryRequest
	4,  // 5: proto.WhitelistService.AddTemporary:input_type -> proto.AddTemporaryRequest
	5,  // 6: proto.WhitelistService.RemoveTemporary:input_type -> proto.RemoveTemporaryRequest
	7,  // 7: proto.WhitelistService.ListPermanent:output_type -> proto.WhitelistDomains
	6,  // 8: proto.WhitelistService.AddPermanent:output_type -> proto.WhitelistDomain
	10, // 9: proto.WhitelistService.RemovePermanent:output_type -> google.protobuf.Empty
	9,  // 10: proto.WhitelistService.ListTemporary:output_type -> proto.WhitelistDomainsTemp
	8,  // 11: proto.WhitelistService.AddTemporary:output_type -> proto.WhitelistDomainTemp
	10, // 12: proto.WhitelistService.RemoveTemporary:output_type -> google.protobuf.Empty
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_whitelist_proto_init() }
func file_whitelist_proto_init() {
	if File_whitelist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_whitelist_proto_rawDesc), len(file_whitelist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_whitelist_proto_goTypes,
		DependencyIndexes: file_whitelist_proto_depIdxs,
		MessageInfos:      file_whitelist_proto_msgTypes,
	}.Build()
	File_whitelist_proto = out.File
	file_whitelist_proto_goTypes = nil
	file_whitelist_proto_depIdxs = nil
}
