services:
  valkey:
    container_name: valkey
    image: valkey/valkey:9.0.3
    ports:
      - 6379:6379 # HOST_PORT:CONTAINER_PORT
    volumes:
      - ./valkey/data:/data
      - ./valkey/conf/valkey.conf:/usr/local/etc/valkey/valkey.conf
    command: ["valkey-server", "/usr/local/etc/valkey/valkey.conf"]
    networks:
      - valkey_network
  redisinsight:
    container_name: redisinsight
    image: redis/redisinsight:latest
    env_file:
      - .env.valkey
    ports:
      - 8001:5540
    networks:
      - valkey_network
    depends_on:
      - valkey
  bdns:
    container_name: bdns
    build:
      context: .
    ports:
      - ${PORT:-853}:${PORT:-853}
    volumes:
      - ${CERT_DIR:-/cert}:/cert #CERT_DIR must be the dir from *outside* the container
    environment:
      KEY_PATH: ${KEY_PATH} # KEY_PATH must be /cert/{FILE_NAME}
      VALKEY_ADDR: ${VALKEY_ADDR}
      CRT_PATH: ${CRT_PATH} # CRT_PATH must be /cert/{FILE_NAME}
      PORT: ${PORT}
    depends_on:
      - valkey
networks:
  valkey_network:
    driver: bridge
