services:
  valkey:
    container_name: valkey
    image: valkey/valkey:9.0.3
    ports:
      - 6379:6379
    volumes:
      - ./valkey/data:/data
      - ./valkey/conf/valkey.conf:/usr/local/etc/valkey/valkey.conf
    command: ["valkey-server", "/usr/local/etc/valkey/valkey.conf"]
    networks:
      - valkey_network
  redisinsight:
    container_name: redisinsight
    image: redis/redisinsight:latest
    env_file:
      - .env.valkey
    ports:
      - 8001:5540
    networks:
      - valkey_network
    depends_on:
      - valkey
  bdns:
    container_name: bdns
    build:
      context: .
    ports:
      - ${PORT:-853}:${PORT:-853}
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/:ro # change if not using letsencrypt
      # letsencrypt uses a symlink, if you add /live to the volume, it will fail
    environment:
      KEY_PATH: ${KEY_PATH:-/etc/letsencrypt/live/dns.example.com/privkey.pem}
      CRT_PATH: ${CRT_PATH:-/etc/letsencrypt/live/dns.example.com/fullchain.pem}
      VALKEY_ADDR: ${VALKEY_ADDR:-valkey:6379}
      PORT: ${PORT:-853}

    depends_on:
      - valkey
    networks:
      - valkey_network

networks:
  valkey_network:
    driver: bridge
